---
# Host-specific storage disk bindings for web-01.
# Uncomment group-specific disks during the demo.

storage_host_pools:
  data_pool:
    disks:
      - /dev/disk/by-id/virtio-data-disk01
  web_content_pool:
    volumes:
      web_content_vol:
        size: 6g
    disks:
      - /dev/disk/by-id/virtio-web-disk01
