---
# Host-specific network identity for db-01.

network_host_overlay:
  primary_dhcp:
    mac: "CHANGE_ME_DB01_DHCP_MAC"

#   static_internal:
#     name: static_internal
#     type: ethernet
#     state: up
#     mac: "CHANGE_ME_DB01_INTERNAL_MAC"
#     ip:
#       address:
#         - CHANGE_ME_DB01_INTERNAL_IP/24
